POST http://localhost:3001/api/persons 
Content-Type: application/json

{
    "name": "ramaFFS", 
    "number": "08582913244"
}

###
POST http://localhost:3001/api/persons 
Content-Type: application/json

{
    "name": "ramasss", 
    "number": "08582913891"
}

###
POST http://localhost:3001/api/persons 
Content-Type: application/json

{
    "name": "rama"
}

###
POST http://localhost:3001/api/persons 
Content-Type: application/json

{
    "number": "08582913891"
}

###
POST http://localhost:3001/api/persons 
Content-Type: application/json

{
}

###
POST https://fullstack-phonebook-app-j7gn.onrender.com/api/persons 
Content-Type: application/json

{
    "name": "rama", 
    "number": "08582913431411"
}
