GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "My Second but actually Third Blog",
  "author": "Your Name",
  "url": "https://example.com/my-first-blog",
  "likes": 0
}

