###
PUT http://localhost:3003/api/blogs/69e225a78b91a4c60174fd58
Content-Type: application/json

{
  "title": "My Updated Blog Title",
  "author": "Your Name",
  "url": "https://example.com/my-first-blog",
  "likes": 0
}